// Code generated by "stringer -type=Status"; DO NOT EDIT.

package document

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusSignRequested-0]
	_ = x[StatusSigned-1]
	_ = x[StatusRejected-2]
	_ = x[StatusVerified-3]
}

const _Status_name = "StatusSignRequestedStatusSignedStatusRejectedStatusVerified"

var _Status_index = [...]uint8{0, 19, 31, 45, 59}

func (i Status) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Status_index)-1 {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[idx]:_Status_index[idx+1]]
}
